# Default values for cloudphone
# This is a YAML-formatted file.

# 全局配置
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

# API 网关配置
apiGateway:
  enabled: true
  replicaCount: 3
  image:
    repository: cloudphone/api-gateway
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
  env:
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "3000"

# 流媒体服务配置
mediaService:
  enabled: true
  replicaCount: 3
  image:
    repository: cloudphone/media-service
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 3003
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

# 调度服务配置
schedulerService:
  enabled: true
  replicaCount: 2
  image:
    repository: cloudphone/scheduler-service
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 3004
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# 计费服务配置
billingService:
  enabled: true
  replicaCount: 2
  image:
    repository: cloudphone/billing-service
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 3006
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# PostgreSQL 配置
postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: cloudphone
  primary:
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1000m"

# Redis 配置
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 5Gi
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# Ingress 配置
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: api.cloudphone.example.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: api-gateway
              port:
                number: 3000
  tls:
    - secretName: cloudphone-tls
      hosts:
        - api.cloudphone.example.com

# 持久化存储配置
persistence:
  enabled: true
  storageClass: "standard"
  accessMode: ReadWriteOnce
  size: 10Gi

# 监控配置
monitoring:
  enabled: false
  prometheus:
    enabled: false
  grafana:
    enabled: false

# 服务账户配置
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod 安全上下文
podSecurityContext:
  fsGroup: 2000

# 安全上下文
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

# Node 选择器
nodeSelector: {}

# 容忍度
tolerations: []

# 亲和性
affinity: {}
