version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:14-alpine
    container_name: cloudphone-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloudphone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: cloudphone-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ 消息队列
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: cloudphone-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO 对象存储
  minio:
    image: minio/minio:latest
    container_name: cloudphone-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Atlas 数据库迁移 - User Service
  atlas-migrate-user:
    image: arigaio/atlas:latest
    container_name: cloudphone-atlas-user
    command: migrate apply --url "postgres://postgres:postgres@postgres:5432/cloudphone?sslmode=disable" --dir "file://migrations"
    working_dir: /app
    volumes:
      - ./backend/user-service/migrations:/app/migrations:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  # Atlas 数据库迁移 - Device Service
  atlas-migrate-device:
    image: arigaio/atlas:latest
    container_name: cloudphone-atlas-device
    command: migrate apply --url "postgres://postgres:postgres@postgres:5432/cloudphone?sslmode=disable" --dir "file://migrations"
    working_dir: /app
    volumes:
      - ./backend/device-service/migrations:/app/migrations:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  # Atlas 数据库迁移 - Billing Service
  atlas-migrate-billing:
    image: arigaio/atlas:latest
    container_name: cloudphone-atlas-billing
    command: migrate apply --url "postgres://postgres:postgres@postgres:5432/cloudphone?sslmode=disable" --dir "file://migrations"
    working_dir: /app
    volumes:
      - ./backend/billing-service/migrations:/app/migrations:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  # Atlas 数据库迁移 - App Service
  atlas-migrate-app:
    image: arigaio/atlas:latest
    container_name: cloudphone-atlas-app
    command: migrate apply --url "postgres://postgres:postgres@postgres:5432/cloudphone?sslmode=disable" --dir "file://migrations"
    working_dir: /app
    volumes:
      - ./backend/app-service/migrations:/app/migrations:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  # Atlas 数据库迁移 - Notification Service
  atlas-migrate-notification:
    image: arigaio/atlas:latest
    container_name: cloudphone-atlas-notification
    command: migrate apply --url "postgres://postgres:postgres@postgres:5432/cloudphone?sslmode=disable" --dir "file://migrations"
    working_dir: /app
    volumes:
      - ./backend/notification-service/migrations:/app/migrations:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  # Atlas 数据库迁移 - API Gateway
  atlas-migrate-api-gateway:
    image: arigaio/atlas:latest
    container_name: cloudphone-atlas-api-gateway
    command: migrate apply --url "postgres://postgres:postgres@postgres:5432/cloudphone?sslmode=disable" --dir "file://migrations"
    working_dir: /app
    volumes:
      - ./backend/api-gateway/migrations:/app/migrations:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  minio_data:
