---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: cloudphone
  labels:
    app: api-gateway
    tier: gateway
spec:
  type: LoadBalancer  # Or ClusterIP if using Ingress
  ports:
    - port: 80
      targetPort: 30000
      protocol: TCP
      name: http
  selector:
    app: api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: cloudphone
  labels:
    app: api-gateway
    tier: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-gateway
        tier: gateway
    spec:
      containers:
      - name: api-gateway
        image: cloudphone/api-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 30000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: cloudphone-shared-config
              key: NODE_ENV
        - name: PORT
          value: "30000"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: cloudphone-secrets
              key: jwt_secret
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: cloudphone-shared-config
              key: USER_SERVICE_URL
        - name: DEVICE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: cloudphone-shared-config
              key: DEVICE_SERVICE_URL
        - name: APP_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: cloudphone-shared-config
              key: APP_SERVICE_URL
        - name: BILLING_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: cloudphone-shared-config
              key: BILLING_SERVICE_URL
        - name: NOTIFICATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: cloudphone-shared-config
              key: NOTIFICATION_SERVICE_URL
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: cloudphone-shared-config
              key: CORS_ORIGIN
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 30000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 30000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: cloudphone
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
