# Prometheus 配置文件
# 云手机平台指标收集

global:
  scrape_interval: 15s      # 默认抓取间隔
  evaluation_interval: 15s  # 规则评估间隔
  
  # 外部标签
  external_labels:
    cluster: 'cloudphone-cluster'
    environment: 'development'

# 告警配置
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

# 规则文件
rule_files:
  - 'alert.rules.yml'

# 抓取配置
scrape_configs:

  # ==========================================
  # Prometheus 自身
  # ==========================================
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
      labels:
        service: 'prometheus'

  # ==========================================
  # Envoy Proxy
  # ==========================================
  - job_name: 'envoy'
    metrics_path: '/stats/prometheus'
    static_configs:
    - targets: ['envoy:9901']
      labels:
        service: 'envoy-gateway'
        role: 'gateway'

  # ==========================================
  # NestJS 微服务（如果暴露了指标）
  # ==========================================
  - job_name: 'nestjs-services'
    static_configs:
    
    # API Gateway
    - targets: ['api-gateway:30000']
      labels:
        service: 'api-gateway'
        app: 'nestjs'
    
    # User Service
    - targets: ['user-service:30001']
      labels:
        service: 'user-service'
        app: 'nestjs'
    
    # Device Service
    - targets: ['device-service:30002']
      labels:
        service: 'device-service'
        app: 'nestjs'
    
    # App Service
    - targets: ['app-service:30003']
      labels:
        service: 'app-service'
        app: 'nestjs'
    
    # Billing Service
    - targets: ['billing-service:30005']
      labels:
        service: 'billing-service'
        app: 'nestjs'
    
    # Notification Service
    - targets: ['notification-service:30006']
      labels:
        service: 'notification-service'
        app: 'nestjs'

  # ==========================================
  # PostgreSQL Exporter（如果部署了）
  # ==========================================
  - job_name: 'postgres'
    static_configs:
    - targets: ['postgres-exporter:9187']
      labels:
        service: 'postgresql'
        database: 'cloudphone'

  # ==========================================
  # Redis Exporter（如果部署了）
  # ==========================================
  - job_name: 'redis'
    static_configs:
    - targets: ['redis-exporter:9121']
      labels:
        service: 'redis'

  # ==========================================
  # RabbitMQ Exporter（如果部署了）
  # ==========================================
  - job_name: 'rabbitmq'
    static_configs:
    - targets: ['rabbitmq:15692']
      labels:
        service: 'rabbitmq'

  # ==========================================
  # Node Exporter（系统指标）
  # ==========================================
  - job_name: 'node'
    static_configs:
    - targets: ['node-exporter:9100']
      labels:
        instance: 'cloudphone-server'

  # ==========================================
  # Consul（如果暴露了指标）
  # ==========================================
  - job_name: 'consul'
    static_configs:
    - targets: ['consul:8500']
      labels:
        service: 'consul'

  # ==========================================
  # 从 Consul 自动发现服务（高级）
  # ==========================================
  - job_name: 'consul-services'
    consul_sd_configs:
    - server: 'consul:8500'
      datacenter: 'dc1'
    
    relabel_configs:
    # 只抓取有 'prometheus' 标签的服务
    - source_labels: [__meta_consul_tags]
      regex: '.*,prometheus,.*'
      action: keep
    
    # 设置实例标签
    - source_labels: [__meta_consul_service]
      target_label: service
    
    # 设置地址
    - source_labels: [__meta_consul_address]
      regex: '(.+)'
      target_label: __address__
      replacement: '${1}:${__meta_consul_service_port}'
