---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: cloudphone
  labels:
    app: rabbitmq
    tier: messaging
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: amqp
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: management
  selector:
    app: rabbitmq
  clusterIP: None  # Headless service for StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: cloudphone
  labels:
    app: rabbitmq
    tier: messaging
spec:
  serviceName: rabbitmq-service
  replicas: 1  # Single instance (for HA, use RabbitMQ cluster)
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        tier: messaging
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: cloudphone-secrets
              key: rabbitmq_user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: cloudphone-secrets
              key: rabbitmq_password
        - name: RABBITMQ_DEFAULT_VHOST
          value: "/cloudphone"
        - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
          value: "-rabbit log_levels [{connection,error},{default,error}]"
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        - name: rabbitmq-config
          mountPath: /etc/rabbitmq
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - -q
            - ping
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - -q
            - check_running
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: rabbitmq-config
        configMap:
          name: rabbitmq-config
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: cloudphone
data:
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_peer_discovery_k8s].
  rabbitmq.conf: |
    # RabbitMQ Configuration for Cloud Phone Platform

    # Network
    listeners.tcp.default = 5672

    # Management Plugin
    management.tcp.port = 15672
    management.tcp.ip = 0.0.0.0

    # Virtual Host
    default_vhost = /cloudphone

    # Memory & Disk
    vm_memory_high_watermark.relative = 0.6
    vm_memory_high_watermark_paging_ratio = 0.75
    disk_free_limit.absolute = 2GB

    # Queue Settings
    queue_master_locator = min-masters

    # Logging
    log.console = true
    log.console.level = info

    # Heartbeat
    heartbeat = 60

    # Connection Settings
    channel_max = 2048
    connection_max = 4096

    # Performance Tuning
    collect_statistics_interval = 10000
