import { MigrationInterface, QueryRunner } from "typeorm";

export class FixSchemaMismatch1763775787514 implements MigrationInterface {
    name = 'FixSchemaMismatch1763775787514'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "activity_participations" DROP CONSTRAINT "fk_participation_activity"`);
        await queryRunner.query(`DROP INDEX "public"."idx_withdraw_records_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_withdraw_records_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_withdraw_records_applied_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_referral_records_referrer_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_referral_records_referee_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_referral_records_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_referral_configs_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_referral_configs_invite_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_earnings_records_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_earnings_records_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_earnings_records_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_user_paid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_status_paid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_paid_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_method_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_order_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_invoices_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_invoices_due_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_coupons_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_coupons_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_coupons_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_coupons_activity_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_coupons_end_time"`);
        await queryRunner.query(`DROP INDEX "public"."idx_coupons_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_usage_records_user_time"`);
        await queryRunner.query(`DROP INDEX "public"."idx_usage_records_user_cost"`);
        await queryRunner.query(`DROP INDEX "public"."idx_usage_records_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_usage_records_device_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_usage_records_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_participations_activity_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_participations_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_participations_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_participations_participated_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_activities_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_activities_time_range"`);
        await queryRunner.query(`DROP INDEX "public"."idx_activities_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_activities_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_activities_start_time"`);
        await queryRunner.query(`DROP INDEX "public"."idx_activities_end_time"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_balances_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_balances_user_id"`);
        await queryRunner.query(`ALTER TABLE "activity_participations" DROP CONSTRAINT "uk_participation_activity_user"`);
        await queryRunner.query(`COMMENT ON TABLE "withdraw_records" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "referral_records" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "referral_configs" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "earnings_records" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "coupons" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "activity_participations" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "activities" IS NULL`);
        await queryRunner.query(`CREATE TABLE "billing_warning_configs" ("userId" uuid NOT NULL, "dailyBudget" numeric(10,2) NOT NULL DEFAULT '100', "monthlyBudget" numeric(10,2) NOT NULL DEFAULT '3000', "lowBalanceThreshold" numeric(10,2) NOT NULL DEFAULT '50', "criticalBalanceThreshold" numeric(10,2) NOT NULL DEFAULT '20', "enableEmailNotification" boolean NOT NULL DEFAULT true, "enableSmsNotification" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b4b4311c88259195563e70db1e8" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`COMMENT ON COLUMN "withdraw_records"."user_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "withdraw_records"."amount" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."withdraw_status" RENAME TO "withdraw_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."withdraw_records_status_enum" AS ENUM('pending', 'approved', 'processing', 'completed', 'rejected', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "withdraw_records" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "withdraw_records" ALTER COLUMN "status" TYPE "public"."withdraw_records_status_enum" USING "status"::"text"::"public"."withdraw_records_status_enum"`);
        await queryRunner.query(`ALTER TABLE "withdraw_records" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."withdraw_status_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "withdraw_records"."status" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."withdraw_method" RENAME TO "withdraw_method_old"`);
        await queryRunner.query(`CREATE TYPE "public"."withdraw_records_method_enum" AS ENUM('alipay', 'wechat', 'bank')`);
        await queryRunner.query(`ALTER TABLE "withdraw_records" ALTER COLUMN "method" TYPE "public"."withdraw_records_method_enum" USING "method"::"text"::"public"."withdraw_records_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."withdraw_method_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "withdraw_records"."method" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "withdraw_records"."fee" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "withdraw_records"."actual_amount" IS NULL`);
        await queryRunner.query(`ALTER TABLE "withdraw_records" ALTER COLUMN "applied_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "withdraw_records" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "withdraw_records" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_records"."referrer_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_records"."referee_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "referral_records" DROP CONSTRAINT "uk_referee_id"`);
        await queryRunner.query(`ALTER TYPE "public"."referral_status" RENAME TO "referral_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."referral_records_status_enum" AS ENUM('pending', 'confirmed', 'rewarded', 'expired')`);
        await queryRunner.query(`ALTER TABLE "referral_records" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "referral_records" ALTER COLUMN "status" TYPE "public"."referral_records_status_enum" USING "status"::"text"::"public"."referral_records_status_enum"`);
        await queryRunner.query(`ALTER TABLE "referral_records" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."referral_status_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_records"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_records"."reward" IS NULL`);
        await queryRunner.query(`ALTER TABLE "referral_records" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "referral_records" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_configs"."user_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_configs"."invite_code" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_configs"."available_balance" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_configs"."frozen_balance" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_configs"."total_earned" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_configs"."total_withdrawn" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_configs"."total_invites" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_configs"."confirmed_invites" IS NULL`);
        await queryRunner.query(`ALTER TABLE "referral_configs" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "referral_configs" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "earnings_records"."user_id" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."earnings_type" RENAME TO "earnings_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."earnings_records_type_enum" AS ENUM('invite', 'bonus', 'other')`);
        await queryRunner.query(`ALTER TABLE "earnings_records" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "earnings_records" ALTER COLUMN "type" TYPE "public"."earnings_records_type_enum" USING "type"::"text"::"public"."earnings_records_type_enum"`);
        await queryRunner.query(`ALTER TABLE "earnings_records" ALTER COLUMN "type" SET DEFAULT 'invite'`);
        await queryRunner.query(`DROP TYPE "public"."earnings_type_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "earnings_records"."type" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "earnings_records"."amount" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "earnings_records"."description" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "earnings_records"."related_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "earnings_records" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "refundAmount" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."code" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."name" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."coupon_type" RENAME TO "coupon_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."coupons_type_enum" AS ENUM('discount', 'cash', 'gift')`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "type" TYPE "public"."coupons_type_enum" USING "type"::"text"::"public"."coupons_type_enum"`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "type" SET DEFAULT 'discount'`);
        await queryRunner.query(`DROP TYPE "public"."coupon_type_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."type" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."value" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."min_amount" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."coupon_status" RENAME TO "coupon_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."coupons_status_enum" AS ENUM('available', 'used', 'expired')`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "status" TYPE "public"."coupons_status_enum" USING "status"::"text"::"public"."coupons_status_enum"`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "status" SET DEFAULT 'available'`);
        await queryRunner.query(`DROP TYPE "public"."coupon_status_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."user_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."activity_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."activity_title" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."start_time" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."end_time" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."order_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."used_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "activity_participations"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activity_participations"."activity_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "activity_participations" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "activity_participations" ADD "user_id" character varying NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activity_participations"."rewards" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."participation_status" RENAME TO "participation_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."activity_participations_status_enum" AS ENUM('pending', 'completed', 'failed')`);
        await queryRunner.query(`ALTER TABLE "activity_participations" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "activity_participations" ALTER COLUMN "status" TYPE "public"."activity_participations_status_enum" USING "status"::"text"::"public"."activity_participations_status_enum"`);
        await queryRunner.query(`ALTER TABLE "activity_participations" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."participation_status_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "activity_participations"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activity_participations"."participated_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "activity_participations" ALTER COLUMN "participated_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."title" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."description" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."activity_type" RENAME TO "activity_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."activities_type_enum" AS ENUM('discount', 'gift', 'flash_sale', 'new_user')`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "type" TYPE "public"."activities_type_enum" USING "type"::"text"::"public"."activities_type_enum"`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "type" SET DEFAULT 'discount'`);
        await queryRunner.query(`DROP TYPE "public"."activity_type_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."type" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."activity_status" RENAME TO "activity_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."activities_status_enum" AS ENUM('upcoming', 'ongoing', 'ended')`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "status" TYPE "public"."activities_status_enum" USING "status"::"text"::"public"."activities_status_enum"`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "status" SET DEFAULT 'upcoming'`);
        await queryRunner.query(`DROP TYPE "public"."activity_status_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."start_time" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."end_time" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."cover_image" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."banner_image" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."rules" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."discount" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."max_participants" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."current_participants" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."rewards" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."conditions" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."is_active" IS NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_7f2de9cd08cfe2b23d99b88d53" ON "withdraw_records" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1aaad1a5d1bd06dd0db16dfa68" ON "withdraw_records" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_410902153005c9158ce12bacae" ON "referral_records" ("referrer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a2818aff7cd555d4f6fcfa89c0" ON "referral_records" ("referee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad6a6dfdea88b521141efff543" ON "referral_records" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_85d5b198974a625fe67173de5f" ON "referral_configs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4b088128e5bc1d7f4a743ccc1" ON "referral_configs" ("invite_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f9d01ff5fdd7169a60d4437f1" ON "earnings_records" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_54955615e849ce0436ba7c7f6e" ON "earnings_records" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_e025109230e82925843f2a14c4" ON "coupons" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed793a952de93a5f8d5dfdace5" ON "coupons" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_9974c02e617aa96ddafd840432" ON "coupons" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7547a38a7f07dd363e09739b1d" ON "coupons" ("activity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2f0372e0d3101eca757117606c" ON "coupons" ("end_time") `);
        await queryRunner.query(`ALTER TABLE "activity_participations" ADD CONSTRAINT "FK_c33cdc666e7b4c0ae07b5c8f8e8" FOREIGN KEY ("activity_id") REFERENCES "activities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "activity_participations" DROP CONSTRAINT "FK_c33cdc666e7b4c0ae07b5c8f8e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f0372e0d3101eca757117606c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7547a38a7f07dd363e09739b1d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9974c02e617aa96ddafd840432"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed793a952de93a5f8d5dfdace5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e025109230e82925843f2a14c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54955615e849ce0436ba7c7f6e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f9d01ff5fdd7169a60d4437f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4b088128e5bc1d7f4a743ccc1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85d5b198974a625fe67173de5f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad6a6dfdea88b521141efff543"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2818aff7cd555d4f6fcfa89c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_410902153005c9158ce12bacae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1aaad1a5d1bd06dd0db16dfa68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f2de9cd08cfe2b23d99b88d53"`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."is_active" IS '是否激活'`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."conditions" IS '参与条件（JSON）'`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."rewards" IS '奖励列表（JSON）'`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."current_participants" IS '当前参与人数'`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."max_participants" IS '最大参与人数'`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."discount" IS '折扣率'`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."rules" IS '活动规则'`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."banner_image" IS '横幅图片URL'`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."cover_image" IS '封面图片URL'`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."end_time" IS '结束时间'`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."start_time" IS '开始时间'`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."status" IS '活动状态'`);
        await queryRunner.query(`CREATE TYPE "public"."activity_status_old" AS ENUM('upcoming', 'ongoing', 'ended')`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "status" TYPE "public"."activity_status_old" USING "status"::"text"::"public"."activity_status_old"`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "status" SET DEFAULT 'upcoming'`);
        await queryRunner.query(`DROP TYPE "public"."activities_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."activity_status_old" RENAME TO "activity_status"`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."type" IS '活动类型'`);
        await queryRunner.query(`CREATE TYPE "public"."activity_type_old" AS ENUM('discount', 'gift', 'flash_sale', 'new_user')`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "type" TYPE "public"."activity_type_old" USING "type"::"text"::"public"."activity_type_old"`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "type" SET DEFAULT 'discount'`);
        await queryRunner.query(`DROP TYPE "public"."activities_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."activity_type_old" RENAME TO "activity_type"`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."description" IS '活动描述'`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."title" IS '活动标题'`);
        await queryRunner.query(`COMMENT ON COLUMN "activities"."id" IS '活动ID'`);
        await queryRunner.query(`ALTER TABLE "activity_participations" ALTER COLUMN "participated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "activity_participations"."participated_at" IS '参与时间'`);
        await queryRunner.query(`COMMENT ON COLUMN "activity_participations"."status" IS '参与状态'`);
        await queryRunner.query(`CREATE TYPE "public"."participation_status_old" AS ENUM('pending', 'completed', 'failed')`);
        await queryRunner.query(`ALTER TABLE "activity_participations" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "activity_participations" ALTER COLUMN "status" TYPE "public"."participation_status_old" USING "status"::"text"::"public"."participation_status_old"`);
        await queryRunner.query(`ALTER TABLE "activity_participations" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."activity_participations_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."participation_status_old" RENAME TO "participation_status"`);
        await queryRunner.query(`COMMENT ON COLUMN "activity_participations"."rewards" IS '获得的奖励（JSON）'`);
        await queryRunner.query(`ALTER TABLE "activity_participations" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "activity_participations" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "activity_participations"."activity_id" IS '活动ID'`);
        await queryRunner.query(`COMMENT ON COLUMN "activity_participations"."id" IS '参与记录ID'`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."used_at" IS '使用时间'`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."order_id" IS '使用的订单ID'`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."end_time" IS '失效时间'`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."start_time" IS '生效时间'`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."activity_title" IS '活动标题'`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."activity_id" IS '活动ID'`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."user_id" IS '用户ID'`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."status" IS '优惠券状态'`);
        await queryRunner.query(`CREATE TYPE "public"."coupon_status_old" AS ENUM('available', 'used', 'expired')`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "status" TYPE "public"."coupon_status_old" USING "status"::"text"::"public"."coupon_status_old"`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "status" SET DEFAULT 'available'`);
        await queryRunner.query(`DROP TYPE "public"."coupons_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."coupon_status_old" RENAME TO "coupon_status"`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."min_amount" IS '最低消费金额'`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."value" IS '面额或折扣率'`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."type" IS '优惠券类型'`);
        await queryRunner.query(`CREATE TYPE "public"."coupon_type_old" AS ENUM('discount', 'cash', 'gift')`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "type" TYPE "public"."coupon_type_old" USING "type"::"text"::"public"."coupon_type_old"`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "type" SET DEFAULT 'discount'`);
        await queryRunner.query(`DROP TYPE "public"."coupons_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."coupon_type_old" RENAME TO "coupon_type"`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."name" IS '优惠券名称'`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."code" IS '优惠券代码'`);
        await queryRunner.query(`COMMENT ON COLUMN "coupons"."id" IS '优惠券ID'`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "refundAmount" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "earnings_records" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "earnings_records"."related_id" IS '关联ID'`);
        await queryRunner.query(`COMMENT ON COLUMN "earnings_records"."description" IS '描述'`);
        await queryRunner.query(`COMMENT ON COLUMN "earnings_records"."amount" IS '金额'`);
        await queryRunner.query(`COMMENT ON COLUMN "earnings_records"."type" IS '收益类型'`);
        await queryRunner.query(`CREATE TYPE "public"."earnings_type_old" AS ENUM('invite', 'bonus', 'other')`);
        await queryRunner.query(`ALTER TABLE "earnings_records" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "earnings_records" ALTER COLUMN "type" TYPE "public"."earnings_type_old" USING "type"::"text"::"public"."earnings_type_old"`);
        await queryRunner.query(`ALTER TABLE "earnings_records" ALTER COLUMN "type" SET DEFAULT 'invite'`);
        await queryRunner.query(`DROP TYPE "public"."earnings_records_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."earnings_type_old" RENAME TO "earnings_type"`);
        await queryRunner.query(`COMMENT ON COLUMN "earnings_records"."user_id" IS '用户ID'`);
        await queryRunner.query(`ALTER TABLE "referral_configs" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "referral_configs" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_configs"."confirmed_invites" IS '确认的邀请人数'`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_configs"."total_invites" IS '总邀请人数'`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_configs"."total_withdrawn" IS '总提现金额'`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_configs"."total_earned" IS '总收益'`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_configs"."frozen_balance" IS '冻结余额'`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_configs"."available_balance" IS '可提现余额'`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_configs"."invite_code" IS '邀请码'`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_configs"."user_id" IS '用户ID'`);
        await queryRunner.query(`ALTER TABLE "referral_records" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "referral_records" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_records"."reward" IS '奖励金额'`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_records"."status" IS '邀请状态'`);
        await queryRunner.query(`CREATE TYPE "public"."referral_status_old" AS ENUM('pending', 'confirmed', 'rewarded', 'expired')`);
        await queryRunner.query(`ALTER TABLE "referral_records" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "referral_records" ALTER COLUMN "status" TYPE "public"."referral_status_old" USING "status"::"text"::"public"."referral_status_old"`);
        await queryRunner.query(`ALTER TABLE "referral_records" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."referral_records_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."referral_status_old" RENAME TO "referral_status"`);
        await queryRunner.query(`ALTER TABLE "referral_records" ADD CONSTRAINT "uk_referee_id" UNIQUE ("referee_id")`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_records"."referee_id" IS '被邀请人ID'`);
        await queryRunner.query(`COMMENT ON COLUMN "referral_records"."referrer_id" IS '邀请人ID'`);
        await queryRunner.query(`ALTER TABLE "withdraw_records" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "withdraw_records" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "withdraw_records" ALTER COLUMN "applied_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "withdraw_records"."actual_amount" IS '实际到账金额'`);
        await queryRunner.query(`COMMENT ON COLUMN "withdraw_records"."fee" IS '手续费'`);
        await queryRunner.query(`COMMENT ON COLUMN "withdraw_records"."method" IS '提现方式'`);
        await queryRunner.query(`CREATE TYPE "public"."withdraw_method_old" AS ENUM('alipay', 'wechat', 'bank')`);
        await queryRunner.query(`ALTER TABLE "withdraw_records" ALTER COLUMN "method" TYPE "public"."withdraw_method_old" USING "method"::"text"::"public"."withdraw_method_old"`);
        await queryRunner.query(`DROP TYPE "public"."withdraw_records_method_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."withdraw_method_old" RENAME TO "withdraw_method"`);
        await queryRunner.query(`COMMENT ON COLUMN "withdraw_records"."status" IS '提现状态'`);
        await queryRunner.query(`CREATE TYPE "public"."withdraw_status_old" AS ENUM('pending', 'approved', 'processing', 'completed', 'rejected', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "withdraw_records" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "withdraw_records" ALTER COLUMN "status" TYPE "public"."withdraw_status_old" USING "status"::"text"::"public"."withdraw_status_old"`);
        await queryRunner.query(`ALTER TABLE "withdraw_records" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."withdraw_records_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."withdraw_status_old" RENAME TO "withdraw_status"`);
        await queryRunner.query(`COMMENT ON COLUMN "withdraw_records"."amount" IS '提现金额'`);
        await queryRunner.query(`COMMENT ON COLUMN "withdraw_records"."user_id" IS '用户ID'`);
        await queryRunner.query(`DROP TABLE "billing_warning_configs"`);
        await queryRunner.query(`COMMENT ON TABLE "activities" IS '营销活动表'`);
        await queryRunner.query(`COMMENT ON TABLE "activity_participations" IS '活动参与记录表'`);
        await queryRunner.query(`COMMENT ON TABLE "coupons" IS '优惠券表'`);
        await queryRunner.query(`COMMENT ON TABLE "earnings_records" IS '收益记录表'`);
        await queryRunner.query(`COMMENT ON TABLE "referral_configs" IS '邀请配置表'`);
        await queryRunner.query(`COMMENT ON TABLE "referral_records" IS '邀请记录表'`);
        await queryRunner.query(`COMMENT ON TABLE "withdraw_records" IS '提现记录表'`);
        await queryRunner.query(`ALTER TABLE "activity_participations" ADD CONSTRAINT "uk_participation_activity_user" UNIQUE ("activity_id", "user_id")`);
        await queryRunner.query(`CREATE INDEX "idx_user_balances_user_id" ON "user_balances" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_user_balances_user" ON "user_balances" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_activities_end_time" ON "activities" ("end_time") `);
        await queryRunner.query(`CREATE INDEX "idx_activities_start_time" ON "activities" ("start_time") `);
        await queryRunner.query(`CREATE INDEX "idx_activities_status" ON "activities" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_activities_type" ON "activities" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_activities_time_range" ON "activities" ("start_time", "end_time") `);
        await queryRunner.query(`CREATE INDEX "idx_activities_is_active" ON "activities" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_participations_participated_at" ON "activity_participations" ("participated_at") `);
        await queryRunner.query(`CREATE INDEX "idx_participations_status" ON "activity_participations" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_participations_user_id" ON "activity_participations" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_participations_activity_id" ON "activity_participations" ("activity_id") `);
        await queryRunner.query(`CREATE INDEX "idx_usage_records_created_at" ON "usage_records" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_usage_records_device_id" ON "usage_records" ("deviceId") `);
        await queryRunner.query(`CREATE INDEX "idx_usage_records_user_id" ON "usage_records" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_usage_records_user_cost" ON "usage_records" ("userId", "cost") WHERE (cost > (0)::numeric)`);
        await queryRunner.query(`CREATE INDEX "idx_usage_records_user_time" ON "usage_records" ("userId", "startTime") `);
        await queryRunner.query(`CREATE INDEX "idx_coupons_user_status" ON "coupons" ("status", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_coupons_end_time" ON "coupons" ("end_time") `);
        await queryRunner.query(`CREATE INDEX "idx_coupons_activity_id" ON "coupons" ("activity_id") `);
        await queryRunner.query(`CREATE INDEX "idx_coupons_user_id" ON "coupons" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_coupons_status" ON "coupons" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_coupons_code" ON "coupons" ("code") `);
        await queryRunner.query(`CREATE INDEX "idx_invoices_due_date" ON "invoices" ("dueDate") `);
        await queryRunner.query(`CREATE INDEX "idx_invoices_user_status" ON "invoices" ("userId", "status", "createdAt") WHERE ("userId" IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_payments_created_at" ON "payments" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_order_id" ON "payments" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_user_status" ON "payments" ("user_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_method_status" ON "payments" ("method", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_created_at" ON "orders" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_user_status" ON "orders" ("userId", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_paid_date" ON "orders" ("paidAt") WHERE (status = 'paid'::orders_status_enum)`);
        await queryRunner.query(`CREATE INDEX "idx_orders_status_paid" ON "orders" ("status", "paidAt") WHERE ("paidAt" IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_orders_user_paid" ON "orders" ("userId", "paidAt") WHERE ((status = 'paid'::orders_status_enum) AND ("paidAt" IS NOT NULL))`);
        await queryRunner.query(`CREATE INDEX "idx_earnings_records_created_at" ON "earnings_records" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_earnings_records_type" ON "earnings_records" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_earnings_records_user_id" ON "earnings_records" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_referral_configs_invite_code" ON "referral_configs" ("invite_code") `);
        await queryRunner.query(`CREATE INDEX "idx_referral_configs_user_id" ON "referral_configs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_referral_records_status" ON "referral_records" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_referral_records_referee_id" ON "referral_records" ("referee_id") `);
        await queryRunner.query(`CREATE INDEX "idx_referral_records_referrer_id" ON "referral_records" ("referrer_id") `);
        await queryRunner.query(`CREATE INDEX "idx_withdraw_records_applied_at" ON "withdraw_records" ("applied_at") `);
        await queryRunner.query(`CREATE INDEX "idx_withdraw_records_status" ON "withdraw_records" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_withdraw_records_user_id" ON "withdraw_records" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "activity_participations" ADD CONSTRAINT "fk_participation_activity" FOREIGN KEY ("activity_id") REFERENCES "activities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
