apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudphone-config
data:
  db_host: "postgres-service"
  db_port: "5432"
  db_database: "cloudphone"
  redis_host: "redis-service"
  redis_port: "6379"
  rabbitmq_host: "rabbitmq-service"
  rabbitmq_port: "5672"
